name: Push to GCR GitHub Action
on: 
  workflow_dispatch:
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-18.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout submoduel
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.SUB_MODULE_TOKEN }}

      - name: GCP Auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCLOUD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}

      - name: Push to GCR
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          # gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }} # can be base64 encoded or plain text || not needed if you use google-github-actions/auth
          registry: gcr.io
          project_id: shoet-blog
          image_name: shoet-blog
          image_tag: latest,v1
          dockerfile: ./deploy/prod/Dockerfile
          context: .
